### ISSUE TITLE
KeyError: 'processed_path' during Preprocess receptors step

### ISSUE THREAD

**Issue by rectuSinister** [YuzheWangPKU/DiffPepBuilder#9]
Hello,
I keep getting the _KeyError: 'processed_path'_ message when attempting to upload a PDB and specify a motif/hotspots during receptor preprocessing. I assume it is a mistake on my end with the nomenclature of my contigs. Is there more detailed documentation regarding how to specify target chains, hotspots, and motifs? I am confused by the ALK1 example as the hotspots and motif fields specify _"B40,B58,B59..."_ but chain B in PDB 6SF1 corresponds to the BMP10 ligand and not the ALK1 receptor (which is chain A). Why would you specify hotspots on the native ligand, or does the 'B' prefix correspond to something else? Any help is appreciated, I hope to use your model soon.

**Comment by YuzheWangPKU** [comment]
Hi there! Please manually delete the `*_processed.pdb` files in the folder containing the receptor files if you intend to rerun the generation process. Otherwise, the script will attempt to reprocess these files, which can cause the error you encountered.

Thanks for flagging this! We’re working on updating the script to handle this automatically.
